
# nothing to generate for Figure1 ...

echo "Main Fig 2 ...."
# Fig2...
# no rguments for figure2 ...
# it generates 4 panels than gues them with montage from ImageMagic ...
python DONE_MainFig2.py

echo "Main Fig 3,4,5,6 ...."
# Fig3,4,5,6...
# next script is based on DONE_brooms_MJ99_Argentina.py ...
# python will be launched 4 times to generate precursors for images 3,4,5 and even part of 6th from the main text ...
# along with some precursors for SuppFigures ...
sh DONE_Fig5_combined.sh


echo "Main Fig 6 remaining pieces ..."
# Fig6...
# it generates Fig6 (main text) - naming misconception going on here, keep it as is for a while ...
# BEWARE this script requires one piece from `DONE_Fig5_combined.sh`!
sh DONE_Fig7_combined.sh



echo "Recalculating Cherry analysis stuff (Bacter - takes long) ..."
# calculate Cherry test here ...
cd ../BOOTSTRAPS
python Cherry_composition_analysis_Thermo_Rnd_PUB_II.py


echo "Recalculating Cherry analysis stuff (Arch) ..."
cd ../ArchNew/BOOTSTRAP
python Cherry_composition_analysis_Thermo_Rnd_PUB_II.py

echo "Almost there , final assembly for Fig 7 ..."
# get back to Publications ...
cd ../../Publication

# Fig7...
# next script merely glues a couple of pics from "../BOOTSTRAPS/" and "../ArchNew/BOOTSTRAP/"
# it generates SuppFig8 and 9 along with the main text figure.
# BEWARE naming misconception for SuppFigs is present here as well ...
sh DONE_Fig7_quintile_Supp89.sh




# that's would be it! ...
# we can add all dependecies for SuppFigs, but maybe later ...